### ISSUE TITLE
Maximum recursion depth exceeded on csv, sqlite, etc.

### ISSUE THREAD

**Issue by acbart** [ContinuumIO/into#67]
The following code is failing for me on Windows, Python 2.7:

    >>> from into import into
    >>> into(list, 'test.csv')
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Python27\lib\site-packages\multipledispatch\dispatcher.py", line 163, in __call__
        return func(*args, **kwargs)
    File "C:\Python27\lib\site-packages\into\into.py", line 79, in into_string_string
        r = resource(b, **kwargs)
    File "C:\Python27\lib\site-packages\into\regex.py", line 64, in __call__
        return self.dispatch(s)(s, *args, **kwargs)
    File "C:\Python27\lib\site-packages\into\directory.py", line 57, in resource_directory
        subtype = type(resource(one_uri, **kwargs))
    File "C:\Python27\lib\site-packages\into\regex.py", line 64, in __call__
        return self.dispatch(s)(s, *args, **kwargs)
    ...
    File "C:\Python27\lib\site-packages\into\regex.py", line 64, in __call__
        return self.dispatch(s)(s, *args, **kwargs)
    File "C:\Python27\lib\site-packages\into\directory.py", line 54, in resource_directory
        one_uri = first(glob(uri))
    File "C:\Python27\lib\glob.py", line 27, in glob
        return list(iglob(pathname))
    File "C:\Python27\lib\glob.py", line 38, in iglob
        if not has_magic(pathname):

The contents of 'test.csv':

    Test,File
    1,2
    3,4
    5,6

I'm pretty new to this system, just saw it on the blogpost. Is 2.7 not supported, have I done something fundamentally wrong, or have I found a bug? I pretty much can't get anything to work beyond simple built-in types:

    >>> into(list, {1,2,3,4,5})
    [1, 2, 3, 4, 5]

**Comment by mrocklin** [comment]
If you update from master things are quite a bit better

    pip install https://github.com/ContinuumIO/into --upgrade

Long story short, we thought that we were testing on Windows but weren't
and a lot of tiny-but-debilitating bugs crept in.  Most of these issues are
fixed.

**Comment by mrocklin** [comment]
into tests are now passing on windows builds.  I'm going to close this.  Looks like part of my message from last time was cut off so I'll repeat it here

    pip install https://github.com/ContinuumIO/into --upgrade

Long story short, we thought that we were testing on Windows but weren't and a lot of tiny-but-debilitating bugs crept in.  Most of these issues have been fixed.  Those that haven't have been given clear warnings (notably `h5py`/`pytables` incompatibility.)

If these issues persist please let me know by raising more issues.

Thank you again for reporting.
